default:
  tags:
    - ubuntu
    - docker

fmt:
  image:
    name: hashicorp/terraform:1.3.9
    entrypoint: [""]
  script:
    - terraform fmt -check -diff

lint:
  image:
    name: ghcr.io/terraform-linters/tflint-bundle:v0.45.0.0
    entrypoint: [""]
  script:
    - tflint --init
    - tflint --format compact
